# Generated by Django 5.1.4 on 2025-01-14 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_work_start', models.TimeField(default='09:00')),
                ('standard_work_end', models.TimeField(default='17:00')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Base hourly rate for calculations', max_digits=10)),
                ('late_deduction_rate', models.DecimalField(decimal_places=2, help_text='Deduction rate per hour of lateness', max_digits=6)),
                ('early_leave_deduction_rate', models.DecimalField(decimal_places=2, help_text='Deduction rate per hour of early leaving', max_digits=6)),
                ('overtime_fixed_rate', models.DecimalField(decimal_places=2, help_text='Fixed rate per overtime hour', max_digits=6)),
            ],
            options={
                'verbose_name': 'Salary Configuration',
                'verbose_name_plural': 'Salary Configurations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be in format EMP1234', regex='^EMP\\d{4}$')])),
                ('designation', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly base salary amount', max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('fingerprint_data', models.BinaryField(blank=True, null=True)),
                ('fingerprint_template_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('early_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('total_late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_early_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('early_leave_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_additions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee salaries',
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
