# Generated by Django 5.1.4 on 2025-01-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
