# Generated by Django 5.1.4 on 2025-01-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_department_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_work_start', models.TimeField(default='09:00')),
                ('standard_work_end', models.TimeField(default='17:00')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('late_deduction_rate', models.DecimalField(decimal_places=2, help_text='Deduction rate per hour', max_digits=6)),
                ('early_leave_deduction_rate', models.DecimalField(decimal_places=2, help_text='Deduction rate per hour', max_digits=6)),
                ('overtime_rate', models.DecimalField(decimal_places=2, help_text='Additional rate per overtime hour', max_digits=6)),
            ],
            options={
                'verbose_name': 'Salary Configuration',
                'verbose_name_plural': 'Salary Configurations',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_leave_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('total_late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_early_leave_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('late_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('early_leave_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_additions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('final_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
