# Generated by Django 5.1.4 on 2025-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salaryconfiguration_attendance_early_leave_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryconfiguration',
            name='overtime_rate',
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Base hourly rate for calculations', max_digits=10),
        ),
        migrations.AddField(
            model_name='salaryconfiguration',
            name='overtime_fixed_rate',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Fixed rate per overtime hour', max_digits=6),
        ),
        migrations.AlterField(
            model_name='salaryconfiguration',
            name='early_leave_deduction_rate',
            field=models.DecimalField(decimal_places=2, help_text='Deduction rate per hour of early leaving', max_digits=6),
        ),
        migrations.AlterField(
            model_name='salaryconfiguration',
            name='late_deduction_rate',
            field=models.DecimalField(decimal_places=2, help_text='Deduction rate per hour of lateness', max_digits=6),
        ),
    ]
