# Generated by Django 5.1.4 on 2025-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_salaryconfiguration_overtime_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryconfiguration',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, help_text='Base hourly rate for calculations', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryconfiguration',
            name='overtime_fixed_rate',
            field=models.DecimalField(decimal_places=2, help_text='Fixed rate per overtime hour', max_digits=6),
        ),
    ]
