# Generated by Django 5.1.4 on 2025-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_salaryconfiguration_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly base salary amount', max_digits=10),
        ),
    ]
